build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MeshMeshGo add-on"
  org.opencontainers.image.description: "MeshMeshGo add-on."
  org.opencontainers.image.source: "https://github.com/espmeshmesh/meshmeshgo"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  MESHMESHGO_VERSION: "v1.3.8"
